### PR TITLE
413 enriching datasets and region specific functionality

### LINKED ISSUE #413: Enriching Datasets and Region-Specific Functionality
## Summary

Our project currently provides limited dataset support, predominantly defaulting to US-based datasets. We aim to enhance our dataset variety for test data generation to support a diverse range of countries and regions. These enhancements are in line with the specifications found in the Benerator documentation. The primary focus of this expansion will be on the Person, Company, and Address Generators. Additionally, we should carry out rigorous testing on the region functionality to ensure it operates effectively.

## Details

- **Dataset Limitations:** At the moment, the test data generation capabilities of our project are hindered by the limited datasets we have at our disposal. These datasets do not sufficiently represent a wide range of countries. We are aiming to enrich these datasets, expanding their scope to cover multiple regions more robustly.
- **Default Dataset:** The current system defaults to the US dataset when generating test data. We need to implement measures to prevent this automatic reversion and ensure the dataset specific to the selected region is retained.
- **Region-Specific Functionality:** We intend to incorporate functionality into our data generator that allows users to select specific regions, as outlined in the Benerator documentation. 
- **Person, Company, and Address Generators:** As part of our commitment to enhancing our test data generator, we plan to enrich these specific data generators with comprehensive data from various countries and regions, thereby increasing their effectiveness and versatility.
- **Region Functionality Testing:** To ensure the accuracy of geographical dataset mapping, we will incorporate these aspects into the EE demos. extension should look like similar to this

```xml
	<echo>Running AddressGenerator for different datasets and regions</echo>
	<generate type="AddressDE" count="50" consumer="Preview">
		<attribute name="address" generator="AddressGenerator" dataset="DE"/>
	</generate>
	<generate type="AddressBR" count="50" consumer="Preview">
		<attribute name="address" generator="AddressGenerator" dataset="BR"/>
	</generate>
	<generate type="AddressUS" count="50" consumer="Preview">
		<attribute name="address" generator="AddressGenerator" dataset="US"/>
	</generate>
	<generate type="AddressFR" count="50" consumer="Preview">
		<attribute name="address" generator="AddressGenerator" dataset="FR"/>
	</generate>
	<generate type="AddressBE" count="50" consumer="Preview">
		<attribute name="address" generator="AddressGenerator" dataset="BE"/>
	</generate>

```

## Expected Outcome

Our primary goal is to provide enhanced dataset variety, superior region-specific functionality, and improved Person, Company, and Address Generators for more effective test data generation.

### PR DESCRIPTION
**Pull request by ake2l**
related to #413

### CODE REVIEW

**Comment by ake2l** [comment]
great work @tunglxfast

**Comment by tunglxfast** [comment]
Finished region: "eastern_europe"
There's only "northern_europe" left before finished "europe" region

**Comment by tunglxfast** [comment]
Just add data street for remaining countries. 
But having issue with GB (United Kingdom) data: city data don't have postal code and 608 cities without area code. I will add them later, also with update the documentation.

**Comment by tunglxfast** [comment]
The dataset for Europe is done.
@ake2l and @PeterBrinkhoff, please take a look.

**Comment by ake2l** [comment]
looks great @tunglxfast 👍🏽

**Pull request merged**
