### PR TITLE
Support consumer mongodb saving long value extracted from script with…

### PR DESCRIPTION
**Pull request by dangsg**
… field key

### CODE REVIEW

**Comment by ake2l** [comment]
looks promising , now please extend the tests , we have with a benerator script what is using a json template with these $numberlong and addtional we also need solutions for other mongo db types like ...


In MongoDB, there are several other data types and operators that are similar to $numberLong:

$numberInt: This is used to represent 32-bit integers in MongoDB. It is used to explicitly specify a number as an integer rather than a double.

$numberDecimal: This is used to represent decimal numbers with arbitrary precision in MongoDB. It is useful for financial or scientific calculations where precision is important.

$date: This is used to represent dates in MongoDB. Dates are stored as milliseconds since the Unix epoch (January 1, 1970), which allows for easy manipulation and comparison of dates.

$regex: This is used to represent regular expressions in MongoDB. Regular expressions can be used for complex pattern matching in text fields.

$object: This is used to represent embedded documents in MongoDB. Embedded documents allow for more complex data structures to be stored within a single document.

$array: This is used to represent arrays in MongoDB. Arrays allow for multiple values to be stored within a single field.

$exists: This is used to test for the existence of a field within a document.

These are just a few examples of the many data types and operators available in MongoDB. By using these data types and operators, you can work with more complex data structures and perform more advanced queries in MongoDB.

**Comment by ake2l** [comment]
as just discussed these 3 should be implemented now ... 

$numberInt: This is used to represent 32-bit integers in MongoDB. It is used to explicitly specify a number as an integer rather than a double.

$numberDecimal: This is used to represent decimal numbers with arbitrary precision in MongoDB. It is useful for financial or scientific calculations where precision is important.

$date: This is used to represent dates in MongoDB. Dates are stored as milliseconds since the Unix epoch (January 1, 1970), which allows for easy manipulation and comparison of dates.


the other one can be postponed until we have a customer use case for these

**Comment by dangsg** [comment]
I've updated for data type int, decimal and date. These are samples of JSON template and MongoDB output. 

Screenshot 2023-04-13 at 17 05 38
Screenshot 2023-04-13 at 17 05 04

So far, date type support only the timestamp value. In next phase, we can consider to support another date format when user supplies the specific one in JSON template, like:
{
"birthDate": {
  "$date": "1995-31-10",
  "$dateFormat": "yyyy-MM-dd"
 }
}

**Review by ake2l — APPROVED** [review]
looks good to me

**Pull request merged**
