### PR TITLE
add demo: mongodb-upserter.ben.xml

### PR DESCRIPTION
**Pull request by tunglxfast**
It's a similar way to use Benerator like mongoDB update - upsert:true

### CODE REVIEW

**Comment by tunglxfast** [comment]
I've just add function for delete collection for mongo, please take a look. Thanks.

**Review by PeterBrinkhoff — APPROVED** [review]
thanks a lot, well done

**Comment by tunglxfast** [comment]
I resolved the conflict.

**Review by ake2l — COMMENTED** [review]
top , looks good

**Pull request merged**
